### ISSUE TITLE
Failed to construct 'URL': Invalid URL with `/api` 

### ISSUE THREAD

**Issue by dhoko** [ProtonMail/proton-shared#63]
https://github.com/ProtonMail/proton-shared/blob/master/lib/fetch/helpers.js#L46

The helper doesn't support `/api`, it should as that's a common URL when we deploy. 

ex: `new URL("/api/auth/info");` 
If we detect this, we should concat with `document.URL` 

```js
TypeError: Failed to construct 'URL': Invalid URL
    at l (https://<domain>vendors~index.e2ce06e8.chunk.js:40:304048)
    at https://<domain>vendors~index.e2ce06e8.chunk.js:40:166978
    at we (https://<domain>vendors~index.e2ce06e8.chunk.js:40:167415)
    at https://<domain>vendors~index.e2ce06e8.chunk.js:40:357607
    at r (https://<domain>vendors~index.e2ce06e8.chunk.js:40:169261)
    at https://<domain>vendors~index.e2ce06e8.chunk.js:40:170200
    at f.current (https://<domain>vendors~index.e2ce06e8.chunk.js:40:175478)
    at https://<domain>vendors~index.e2ce06e8.chunk.js:63:87611
    at c (https://<domain>vendors~index.e2ce06e8.chunk.js:40:422128)
    at Generator._invoke (https://<domain>vendors~index.e2ce06e8.chunk.js:40:421916)
```

**Comment by sathia27** [comment]
@dhoko  I have raised Pull request #74 
Please let me know if we need to make any changes.

**Comment by mmso** [comment]
Thanks @sathia27 !

**Comment by sathia27** [comment]
@mmso @dhoko 
Tests are failing due to this merge. I will look into it.

**Comment by mmso** [comment]
@sathia27 yeah just need to change `location.href` -> `window.location.href`

**Comment by sathia27** [comment]
#75 Sent you new PR for the same
